### ISSUE TITLE
Google Playe Game Services integration is not working after upgrading to sound null safety

### ISSUE THREAD

**Issue by MrCsabaToth** [DealORound/Deal-O-Round#20]
```
E/Error   (22698): signInError
E/Error   (22698): com.google.android.gms.common.api.ApiException: 4: 4: 
E/Error   (22698): 	at com.google.android.gms.common.internal.ApiExceptionUtil.fromStatus(com.google.android.gms:play-services-base@@17.1.0:4)
E/Error   (22698): 	at com.google.android.gms.common.internal.zai.zaf(com.google.android.gms:play-services-base@@17.1.0:2)
E/Error   (22698): 	at com.google.android.gms.common.internal.zak.onComplete(com.google.android.gms:play-services-base@@17.1.0:6)
E/Error   (22698): 	at com.google.android.gms.common.api.internal.BasePendingResult.zaa(com.google.android.gms:play-services-base@@17.1.0:176)
E/Error   (22698): 	at com.google.android.gms.common.api.internal.BasePendingResult.setResult(com.google.android.gms:play-services-base@@17.1.0:135)
E/Error   (22698): 	at com.google.android.gms.auth.api.signin.internal.zzi.zzc(com.google.android.gms:play-services-auth@@18.1.0:5)
E/Error   (22698): 	at com.google.android.gms.auth.api.signin.internal.zzs.zzc(com.google.android.gms:play-services-auth@@18.1.0:6)
E/Error   (22698): 	at com.google.android.gms.internal.auth-api.zzc.onTransact(com.google.android.gms:play-services-auth@@18.1.0:13)
E/Error   (22698): 	at android.os.Binder.execTransactInternal(Binder.java:1032)
E/Error   (22698): 	at android.os.Binder.execTransact(Binder.java:1005)
I/ExplicitSignIn(22698): Trying explicit sign in
...
I/flutter (22698): Error signing in: PlatformException(error, Something went wrong Status{statusCode=SIGN_IN_REQUIRED, resolution=null}, null, null)
```

**Comment by MrCsabaToth** [comment]
https://github.com/Abedalkareem/games_services/issues/20

**Comment by MrCsabaToth** [comment]
This might be a debug-only problem and not related to the sound null safety!

**Comment by basicBrogrammer** [comment]
Did you ever figure this out? I'm going to downgrade to the latest stable version to see if it fixes it.

**Comment by MrCsabaToth** [comment]
@basicBrogrammer actually I did. It was a debug only problem. In release it works OK (try to install the game and tell me if it wouldn't work for you).
See https://stackoverflow.com/questions/24408967/google-play-game-services-debug-and-release-certificate or
https://stackoverflow.com/questions/18495075/google-play-services-sign-in-client-id-debug-vs-release
I believe I took care of the SHA1 fingerprint of the debug version, but I'll double check. There is still something which gets in the way in debug mode.

**Comment by EliaTolin** [comment]
@MrCsabaToth Have you fix the problem?

**Comment by MrCsabaToth** [comment]
> @MrCsabaToth Have you fix the problem?

See these replies:
* https://stackoverflow.com/a/62964787/292502
* https://stackoverflow.com/a/62964525/292502

Also note that Flutter adds an extra tech layer onto the technology stack. This problem is at Android level.

**Comment by MrCsabaToth** [comment]
I'd need to retest this, so I'm not closing this issue yet.

**Comment by EliaTolin** [comment]
@MrCsabaToth I use only google not Firebase. But when i create my credentials Play Console suggest SHA1 fingerprint different from SHA1 generate from shell. Is it a problem?

**Comment by MrCsabaToth** [comment]
> @MrCsabaToth I use only google not Firebase. But when i create my credentials Play Console suggest SHA1 fingerprint different from SHA1 generate from shell. Is it a problem?

Yes they are different. What you get from the Play Console are for your final/beta releases (compiled for release, signed, etc). Whereas what the console instructions show you are the fingerprints your debug version is running with. They must differ from the final releases and you have to let the other end (Google) know about your developer fingerprints.

**Comment by EliaTolin** [comment]
> > @MrCsabaToth I use only google not Firebase. But when i create my credentials Play Console suggest SHA1 fingerprint different from SHA1 generate from shell. Is it a problem?
> 
> 
> 
> Yes they are different. What you get from the Play Console are for your final/beta releases (compiled for release, signed, etc). Whereas what the console instructions show you are the fingerprints your debug version is running with. They must differ from the final releases and you have to let the other end (Google) know about your developer fingerprints.

Thanks you.
I try all method but i have same problem.

**Comment by EliaTolin** [comment]
> > @MrCsabaToth I use only google not Firebase. But when i create my credentials Play Console suggest SHA1 fingerprint different from SHA1 generate from shell. Is it a problem?
> 
> Yes they are different. What you get from the Play Console are for your final/beta releases (compiled for release, signed, etc). Whereas what the console instructions show you are the fingerprints your debug version is running with. They must differ from the final releases and you have to let the other end (Google) know about your developer fingerprints.

Hi sorry for disturb, is it possible i need regenerate SHA-1?
I've been trying to solve for 10 days, I'm not going back.

**Comment by MrCsabaToth** [comment]
> > > @MrCsabaToth I use only google not Firebase. But when i create my credentials Play Console suggest SHA1 fingerprint different from SHA1 generate from shell. Is it a problem?
> > 
> > 
> > Yes they are different. What you get from the Play Console are for your final/beta releases (compiled for release, signed, etc). Whereas what the console instructions show you are the fingerprints your debug version is running with. They must differ from the final releases and you have to let the other end (Google) know about your developer fingerprints.
> 
> Hi sorry for disturb, is it possible i need regenerate SHA-1? I've been trying to solve for 10 days, I'm not going back.

There's not enough info and detail about your particular problem so I could help. Please open a StackOverflow issue, describe as much details as possible what you experience, what exact steps you tried, what exact error messages you received. Link the SO issue here so I can look, and as a bonus the whole SO community can look at it too.

**Comment by EliaTolin** [comment]
I solved it, just simply wait a minute for the services to load, then the login screen is shown.

**Comment by MrCsabaToth** [comment]
> I solved it, just simply wait a minute for the services to load, then the login screen is shown.

Interesting! Thanks for letting me know
